@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "User" as User

participant "SmartHome" as SH<<System (C4)>>

User -> SH : I want to get a list of all measurement of a device
activate SH
activate User


SH --> User : Logs in a Device
deactivate SH
deactivate User


@enduml