@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "SmartHome <<System (C4)>>"
    participant "Backend" as BE<<container (C4)>>

end box


HTTP o-> BE : GET/logs temperature difference logs
activate BE


BE -->o HTTP : JSON 200




@enduml