@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "Client" as User


box "SmartHome <<System (C4)>>"
    participant "Frontend" as FE<<container (C4)>>
    participant "Backend" as SV<<container (C4)>>
end box

User -> FE : I want to get a list of all measurement of a device
activate FE
activate User

FE -> SV : GET /logs by device ID and time period
activate SV

SV --> FE : JSON 200
deactivate SV

FE --> User : logs
deactivate FE
deactivate User


@enduml