@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "SmartHome <<System (C4)>>"
    participant "Backend" as BE<<container (C4)>>
end box

HTTP -> BE : POST /sensors
activate BE

BE --> HTTP : JSON 201
deactivate BE

@enduml