@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

actor "Client" as User

    box SmartHome <<System (C4)>>
    participant Frontend as FE<<container (C4)>>
    participant Backend as BE<<container (C4)>>
    end box


User -> FE :  Quero configurar um device, adicionar um sensor
activate FE
activate User

FE -> BE : POST /sensors
activate BE

BE --> FE : JSON 201
deactivate BE

FE --> User : adicionado!
deactivate FE

User -> FE :  Quero configurar um device, adicionar um atuador
activate FE

FE -> BE : POST /actuators
activate BE

BE --> FE :  JSON 201
deactivate BE

FE --> User : adicionado!
deactivate FE

User -> FE :  Quero configurar um device, quero desativar!
activate FE

FE -> BE : PUT /deactivate/{deviceID}
activate BE

BE --> FE :  JSON 201
deactivate BE

FE --> User : desativado!
deactivate FE
deactivate User





@endumll