version: '3.8'

services:
  db:
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - spring-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
  web:
    build:
      context: web
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "7070:80"
    depends_on:
      - web

volumes:
  spring-data: