@startuml
!pragma layout smetana

autonumber

actor "Room Owner or Power User or Admin" as User
participant System

'User -> System: Give me the list of rooms
'System --> User: List of Rooms
'User -> System: Give me the list of devices in this room
'System --> User: List of Devices

ref over User, System: uc6 - get devices in room

User -> System: Select View Logs in Device
activate User
activate System
System -> User: Which time period?
deactivate System
User -> System: Time period
activate System
System --> User: List of Logs
deactivate System
deactivate User

@enduml