@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "Backend" <<Container (C4)>>"
    participant "Server" as SE<<container (C4)>>
    participant "Database" as DB<<container (C4)>>
end box


HTTP o-> SE : POST /sensors
activate SE

SE -> DB : save
activate DB

DB --> SE : sensorDataModel
deactivate DB


SE -->o HTTP : JSON 201
deactivate SE

deactivate HTTP


@enduml