@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

autonumber

participant " " as HTTP

box "Backend" <<Container (C4)>>"
    participant "Server" as SE<<container (C4)>>
    participant "Database" as DB<<container (C4)>>
end box


HTTP o-> SE : GET /devices/{roomId}
activate SE

SE -> DB : findByRoomId
activate DB

DB --> SE : deviceListDataModel
deactivate DB


SE -->o HTTP : JSON 200
deactivate SE

deactivate HTTP


@enduml