@startuml
'https://plantuml.com/class-diagram

!pragma layout smetana
!pragma scale 100 width
!pragma useVerticalIfPossible

package domain.Sensor {
    interface Sensor {
        + getID(): SensorID
        + getName: SensorName
        + getModelPath(): ModelPath
        + getSensorTypeID(): SensorTypeID
        + toString(): String
        + getValue(): ValueObject
        + getDeviceID(): DeviceID
    }

    class AveragePowerConsumptionSensor {
            - _modelPath : ModelPath
            - _sensorName : SensorName
            - _sensorID : SensorID
            - _sensorTypeID : SensorTypeID
            - _AveragePowerConsumptionSensorValue : AveragePowerConsumptionSensorValue
            - _deviceID : DeviceID
            - _dValue : double
            - _powerConsumptions : HashMap<LocalDateTime, Double>

            + AveragePowerConsumptionSensor(deviceID : DeviceID, modelPath : ModelPath, sensorTypeID : SensorTypeID, sensorName : SensorName)
            # addReading(readTime : LocalDateTime, value : double) : double
            + getID() : SensorID
            + getName() : SensorName
            + getModelPath() : ModelPath
            + getSensorTypeID() : SensorTypeID
            + getDeviceID() : DeviceID
            + toString() : String
            + getValue() : ValueObject
            + getValue(initialTime : LocalDateTime, finalTime : LocalDateTime) : ValueObject
        }
}

package valueObject {
    class AveragePowerConsumptionSensorValue {
    - _dValue : double
    + AveragePowerConsumptionSensorValue(dValue : double)
    + getValue() : double
    + toString() : String
    }

    class SensorTypeID {
        - _id: String
        + SensorTypeID(strDescription: String)
        + getId() : String
        + hashCode() : int
        + equals(obj: Object) : boolean
        + toString() : String
    }

    class SensorModelID {
        - _sensorModelID: String
        + SensorModelID(strDescription : String)
        + getId() : String
        + hashCode() : int
        + equals(obj: Object) : boolean
        + toString() : String
    }

    class SensorID {
        - _id: String
        + SensorID(id: String)
        + getID() : String
        + hashCode() : int
        + equals(obj: Object) : boolean
        + toString() : String
    }

    class DeviceID {
        - _id: String
        + DeviceID(String id)
        + getID() : String
        + hashCode() : int
        + equals(obj: Object) : boolean
        + toString() : String
    }

    class ModelPath {
        - _path: String
        + ModelPath(path: String)
        + toString() : String
    }
}

package ddd {

  interface DomainEntity {
  }

  interface DomainID {
  }

  interface AggregateRoot {
  }

  interface ValueObject{
  }
}

AveragePowerConsumptionSensor ..|> domain.Sensor.Sensor

AveragePowerConsumptionSensor"1" --> "1" AveragePowerConsumptionSensorValue : has
AveragePowerConsumptionSensor"1" -->  "1" SensorTypeID : has
AveragePowerConsumptionSensor"1" -->  "1" SensorModelID : has
AveragePowerConsumptionSensor"1" -->  "1" SensorID : has
AveragePowerConsumptionSensor"1" -->  "1" DeviceID : has
AveragePowerConsumptionSensor"1" -->  "1" ModelPath : has

DomainEntity --|> DomainID
AggregateRoot --|> DomainEntity
AggregateRoot --|> DomainID
AveragePowerConsumptionSensorValue ..|> ValueObject

SensorTypeID ..|> ddd.DomainID
SensorModelID ..|> ddd.DomainID
SensorID ..|> ddd.DomainID
DeviceID ..|> ddd.DomainID
ddd.DomainID ..|> ValueObject

@enduml